### ISSUE TITLE
config: Change default logdir and rundir

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#1037]
On RPM install, this is the typical config that gets installed:

```toml
localstatedir = "/var/lib/glusterd2"
logdir = "/var/log/glusterd2"
logfile = "glusterd2.log"
loglevel = "INFO"
rundir = "/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
```

The `logdir` should be `/var/log/glusterfs` and `rundir` should default to `/var/run/gluster`
